### ISSUE TITLE
Helm uninstall does not delete CRDs and persistent volumes 

### ISSUE THREAD

**Issue by semjongeist** [stackabletech/trino-operator#141]
Currently not all resources are correctly deleted via helm uninstall, causing deadlocks when terminating pods (in this case Trino Coordinator / Worker).

Expected state:
When I uninstall an operator (or a stack) I expect all pods/ deployments etc. as well as CRD's and PVC's to be deleted. For critical resources, notification would also be an option.

The deadlocks are not always reproducible as they are also accompanied by bugs in the pods themselves.
However, you can see that the CRD configuration and the PVCs are still there. 
Here is an example:
![image](https://user-images.githubusercontent.com/99405398/154282170-0a308392-c2cc-47a1-9014-4917fb638e1c.png)

**Comment by semjongeist** [comment]
I realized that it has become normal behavior in Kubernetes and is not a bug rather a feature for statefulsets. 
In a productive system, it is to be expected that not everything will break (data is lost, etc).
It's only a bit annoying in the development phase, since you have to delete resources in a certain order. 
Maybe there is the possibility to add an argument to the uninstall that everything should be deleted (at your own risk) -> Feature-Request.

**Comment by lfrancke** [comment]
@sbernauer @teozkr Do you have any input on this ticket for me?

**Comment by sbernauer** [comment]
I didn't understand everything but i took away:
* Trino runs as a sts (StatefulSet) with pvcs mounted. I don't know whats the purpose of the pvcs but fine so far ^^
* When a TrinoCluster CRD is deleted the corresponding sts will be deleted
* The pvcs will *not* be deleted and you would prefer to have to option for that. Obviously not as a default as data loss could occur ;)
I searched a little bit and found https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention. Good news is that we could include that in the Trino CRD (and also other products). Bad news is that the docs talk about a `StatefulSetAutoDeletePVC` feature gate but i have a feeling that the docs are outdated and it should work with recent k8s versions.

Would the persistentvolumeclaim-retention match your requirements? I personally prefer using k8s standard methods instead of writing bash script doing self implemented pvc retention and accidentally deleting a pvc that should not be deleted.

**Comment by semjongeist** [comment]
Hello everyone, 
Sebastian got it right. But is not necessary to implement such a feature (optional, depending on the roadmap/ resources).
I myself have seen in other official Helm charts (like Gitlab) that the PVC's are automatically deleted. 
In a productive system it will almost not happen that a release is suddenly deleted (rather upgraded).

**Comment by lfrancke** [comment]
I'm sorry for being thick:
Do we need to do anything here or not?

**Comment by semjongeist** [comment]
No, the issue can be closed. :)
