### ISSUE TITLE
Port 8080 missing from Service in case tls is disabled

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/trino-operator#299]
### Affected version

0.7.0

### Current and expected behavior

When changing the trino operator from using TLS to non-TLS (see config below), the HTTPS/8443 service is deployed, but not an additional HTTP/8080 service. This means, a loadbalancer in front of trino has issues binding to trino over HTTP, making exposing trino via the LB impossible.
```
config:
  tls: null
  internalTls:
    secretClass: tls
```
I would expect the Pod and Service to expose both, 8080 and 8443. Currently 8080 is missing.

### Possible solution

Workaround: Deploy an additional service handling 8080, which is not

**Comment by lfrancke** [comment]
As this is a bug I'm fine with it being pulled directly into dev or refinement accepted as long as there is room for it and you think a further refinement is not needed.

**Comment by maltesander** [comment]
> I would expect the Pod and Service to expose both, 8080 and 8443. Currently 8080 is missing.

This is not quite true, for exposing ports only the "client" settings should be relevant. In this case it should be only 8080.

> ### Possible solution
> Workaround: Deploy an additional service handling 8080, which is not

The problem is this https://github.com/stackabletech/trino-operator/blob/d8fdf06b0717cf0b3ef392f5663681e026e1f5b2/rust/crd/src/lib.rs#L619

```
/// Returns if the HTTP port should be enabled
pub fn http_port_enabled(&self) -> bool {
    self.get_client_tls().is_none() && self.get_internal_tls().is_none()
}
```

The get_internal_tls() check is wrong here. But i think (did not check) that it is used somewhere else, so we have to look at this carefully.

**Comment by lfrancke** [comment]
But you agree that this is something worth looking at?

**Comment by maltesander** [comment]
Yeah it's definitely a bug :)

**Comment by berndfo** [comment]
verified. 0.8.0-nightly fixes this for me. thank you!
