### ISSUE TITLE
Support Hive storage caching

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/trino-operator#319]
The Trino Hive connector can [cache files accessed from HDFS or object storage locally](https://trino.io/docs/current/connector/hive-caching.html) to improve performance. Without this every query results in remote reads every time they're run.

- The cache is written to a file system on the coordinator and the worker nodes
- One or more PVCs should be provisioned for caching
- These can be RAM disks if there's a need for a high performance cache
- Each connector requires a separate cache directory on the cache volumes

**Comment by soenkeliebau** [comment]
@sbernauer

**Comment by sbernauer** [comment]
Just wanted to mention the following section from https://trino.io/episodes/43.html:
> Hive connector caching
Trino has an [embedded caching engine](https://trino.io/docs/current/connector/hive-caching.html) in the Hive connector. This is convenient as it ships with Trino, however, it does not work outside the Hive connector. The caching engine is [Rubix](https://github.com/qubole/rubix). While this system works for simple Hive use cases, it fails to address use cases outside of Hive and hasn’t been maintained since 2020. There are many features missing like security features and support for more compute engines.

There is also a demo on how to use Trino and Alluxio, which is pretty straight-forward: https://www.youtube.com/watch?v=yaxPEWRpEzc

It *might* be the better solution to use Alluxio, especially as I personally would choose Iceberg over Hive if possible. The embedded caching does only work wit Hive. Alluxio could also be used from within Spark etc.
On the other hand Alluxio needs active components to be deployed.

**Comment by lfrancke** [comment]
@Jimvin You raised this but it seems as if the caching is unmaintained and not actually very useful as @sbernauer said.

Do you think we should pursue this or close it?

**Comment by Jimvin** [comment]
I say close it.
